### ISSUE TITLE
[SUGGESTION] WANNA MAKE ZARRAS PROUD?

### ISSUE THREAD

**Issue by Cuniq** [stevemman/Database-Management-System#1]
# WOW USING UNDERSCORE **"_"** IN A OO PROGRAMMING LANGUAGE

* DUDE
* THAT'S
    * C
    * NOT EVEN ++
          * OLD

**Comment by Cuniq** [comment]
## WOW METHODS STARTING WITH A CAPITAL LETTER

1. ZARRAS
2. WILL
3. H8
4. U
     * PAS KAI GIA VELTIOSH
      * PLEASE FIX

**Comment by stevemman** [comment]
these are standard C# conventions, i would recommend a good C# book. #GETGUD

**Comment by Cuniq** [comment]
thks for the info master. Have some reading to do
